### ISSUE TITLE
premium type activities not showing

### ISSUE THREAD

**Issue by jkoestner** [schmittx/home-assistant-eero#27]
the data_usage, ad_block premium type activity has stopped working for me. This could be from Eero as it used to work for me.

**Comment by sanghviharshit** [comment]
are you using some promo code for eero subscription? I signed up for eero premium through 1Password promo and it stopped working for me as well, because the eero API returns a different premium status which the eero component filters out. I commented out the line of code in the eero component to enable the data_usage and ad_block again

**Comment by sanghviharshit** [comment]
enable the API response logging from the component configuration, find out what's reported in the API response and change this line https://github.com/schmittx/home-assistant-eero/blob/main/custom_components/eero/api/network.py#L319
Mine is `return bool(self.premium_status == "past_due") or bool(self.premium_status == "canceled")`

**Comment by schmittx** [comment]
I believe this should be fixed now in [1.2](https://github.com/schmittx/home-assistant-eero/releases/tag/1.2.0) but let me know if there's still concerns.
