### ISSUE TITLE
Devices connected by type?

### ISSUE THREAD

**Issue by MtlPhil** [schmittx/home-assistant-eero#3]
Great work on this add-on, awesome integration into HA. Question, though: is there any way to have either a sensor (count) or binary sensor detecting a cell (or a member of a profile)? Or whether # devices connected to guest network > 0? The use case would be baby sitter or family member babysitting the kids and connected to wifi, don’t trigger ‘Away’ routines. Thanks!

**Comment by rjbudke** [comment]
I love this idea.

**Comment by schmittx** [comment]
I think I generally know what you want, but I'm a bit unclear on the specifics.

The following entities would be easy enough to create, do any these achieve what you're looking for?

1) A binary sensor that is triggered on when any client is connected to the guest network
2) A sensor showing the number of clients connected to the guest network
3) A binary sensor for each profile that is triggered on when any client within that profile is connected to the **main** network
4) A sensor for each profile showing the number of clients within that profile connected to the **main** network
5) A binary sensor for each profile that is triggered on when any client within that profile is connected to the **guest** network
6) A sensor for each profile showing the number of clients within that profile connected to the **guest** network

Creating entities based on the Eero "type" (i.e. `phone`, `tablet`, `watch`, `laptop`, etc.) may not be the best approach since there's a lot of available types and Eero doesn't always assign the right type by default (would require manually correcting within Eero first and then configuring HA). I think it'd get clunky/cumbersome pretty quickly, but that's my $0.02...

Let me know what your thoughts are.

**Comment by MtlPhil** [comment]
Thanks for trying to decipher my cryptic request, and for the specific
suggestions. I can’t program them but happy to test anything you pull
together if that is useful.

You are right that Eero is imperfect with regards to assigning device types
(though I’ve found they are better with cell phones than other device
types).

If the options you propose, I think 1) and 3) would best achieve what I’m
looking to do, with 3) potentially covering the family member who would
connect to a ‘guest’ profile on the main network while 1) covers the random
baby sitter.

* Your other suggestions are great for other use cases.

You already have a variant of 2) with the # of devices connected to each
Eero device; a filter by network could be useful, though not for the use
case we are discussing.

When I look at 4) and 6), I can definitely see how those would be useful,
if we could add data consumption rather than client count, to track either
a “kid” profile or an “IoT” profile data consumption. Imagine an alternate
universe where Eero becomes more useful and allows for the creation of
VLANs, some measure of consumption by profile / network would be great. But
again, not for this use case.

**Comment by schmittx** [comment]
I just pushed a new release, try it out and let me know of any feedback. I ended up implementing 1/2/3/4 above which should solve your problem.

**Comment by MtlPhil** [comment]
Thank you very much - I will play with it over the weekend and get back to
you.

**Comment by schmittx** [comment]
Closing this for now, if you still have concerns or requests feel free to re-open or create a new issue
