### ISSUE TITLE
Presence detection question

### ISSUE THREAD

**Issue by deadrubberboy** [schmittx/home-assistant-eero#59]
I made a group in eero with my phone.  Is there a way to have that tied to a home assistant user so it shows home/away when phone joins/leaves wifi (eero)?

Basically, can the status I get in HA from your plug in be tied to a HA user?

**Comment by schmittx** [comment]
(I assume "group in eero" means a profile. If not, please clarify and disregard my response below.)

Your comment got me thinking about a worthwhile feature, so I made a quick update.

Beginning with [1.3.3](https://github.com/schmittx/home-assistant-eero/releases/tag/1.3.3), a `device_tracker` entity is now created for each configured profile. This entity represents the cumulative status of all clients in that profile (`home` if any of those clients is connected to the network, `not_home` otherwise).

In addition to that, a `binary_sensor` entity is available for each configured profile and uses the same logic as above.

Finally, a `device_tracker` entity is also created for each individually configured client.

Then, within Home Assistant, you can easily assign any `device_tracker` entity (or multiple) to a user profile for presence detection purposes.

I think this should achieve what (I think) you're looking for. Let me know your feedback.

**Comment by deadrubberboy** [comment]
Yes! You understood correctly and went above and beyond with a solution! Thank you!

I will update and and test asap!

**Comment by deadrubberboy** [comment]
is there a way to update via HA gui? Or do I need to remove and reinstall?

**Comment by deadrubberboy** [comment]
Works! This is awesome!
