### ISSUE TITLE
Home/Away device_tracker does not work correctly for multiple locations (when not all networks are configured as active)

### ISSUE THREAD

**Issue by rsnodgrass** [schmittx/home-assistant-eero#6]
Device tracker sets home/away state regardless of which network a device is configured with.  Does not seem to honor the CONF_NETWORKS setting.

**Comment by rsnodgrass** [comment]
I updated my fork to include extra attributes in device_trackers (e.g. which network it is on)

**Comment by rsnodgrass** [comment]
I have commented out a filter check to ensure clients are on networks that are configured before adding them as a tracking instance.

**Comment by schmittx** [comment]
Sorry for the slow response here.

I want to confirm I understand the problem (since I don't have multiple networks myself).

You've got 2 networks (A and B), but only A is configured. You've then got a client within network A configured as well. The device tracker for the client works properly with regards to network A; **but** if the client is connected to network B then the device tracker shows `Home`. Is that correct?

**Comment by schmittx** [comment]
@rsnodgrass Any update on this? Still struggling with this problem?

**Comment by schmittx** [comment]
Stale, closing for now.
